DROP TABLE IF EXISTS OrderLines;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS ProductTypes;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Customers (
	ID	INT	NOT NULL	IDENTITY(1,1),
	Name	NVARCHAR(MAX)	NOT NULL,
	HouseNo	INT	NOT NULL,
	Streetname NVARCHAR(MAX)	NOT NULL,
	City	NVARCHAR(MAX)	NOT NULL,
	Zip	INT	NOT NULL,
	Email NVARCHAR(MAX)	NOT NULL
CONSTRAINT Customers_PK PRIMARY KEY(ID)
);

CREATE TABLE ProductTypes (
	ID INT NOT NULL	IDENTITY(1,1),
	Description	Text	NOT NULL,
	Price	FLOAT	NOT NULL,
	Amount	INT	NOT NULL,
CONSTRAINT ProductTypes_PK PRIMARY KEY(ID)
	);

CREATE TABLE Orders (
	ID	INT	NOT NULL IDENTITY(1,1),
	OrderDate	DATETIME2	NOT NULL,
	DeliveryDate	DATETIME2 NOT NULL,
	CustomerID	INT	NOT NULL
CONSTRAINT Orders_PK PRIMARY KEY(ID),
CONSTRAINT OdrCst_FK FOREIGN KEY(CustomerID)
	REFERENCES Customers(ID)
);

CREATE TABLE OrderLines (
	ID	INT	NOT NULL IDENTITY(1,1),
	ProductID	INT NOT NULL,
	OrderID	INT	NOT NULL,
	Quantity	INT	NOT NULL,

CONSTRAINT OrderLine_PK PRIMARY KEY(ID),
CONSTRAINT OL_Prdct_FK FOREIGN KEY(ProductID)
	REFERENCES ProductTypes(ID),
CONSTRAINT OL_Ordr_FK FOREIGN KEY(OrderID)
	REFERENCES Orders(ID)
	);